In [1]:
# Imports
import pandas as pd
import numpy as np
import os
from pathlib import Path

C:\Users\jimmy\miniconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
master_df = pd.read_csv('../Data/raw_data/2024/unzipped/hd2024.csv', low_memory=False)
master_df.head()

,UNITID,INSTNM,IALIAS,ADDR,CITY,STABBR,ZIP,FIPS,OBEREG,CHFNM,...,CBSA,CBSATYPE,CSA,COUNTYCD,COUNTYNM,CNGDSTCD,LONGITUD,LATITUDE,DFRCGID,DFRCUSCG
0,100654,Alabama A & M University,AAMU,4900 Meridian Street,Normal,AL,35762,1,5,Dr. Daniel K. Wims,...,26620,1,290,1089,Madison County,105,-86.568502,34.783368,106,1
1,100663,University of Alabama at Birmingham,UAB,Administration Bldg Suite 1070,Birmingham,AL,35294-0110,1,5,Ray L. Watts,...,13820,1,142,1073,Jefferson County,107,-86.799345,33.505697,91,1
2,100690,Amridge University,Southern Christian University Regions University,1200 Taylor Rd,Montgomery,AL,36117-3553,1,5,Michael C.Turner,...,33860,1,388,1101,Montgomery County,102,-86.174010,32.362609,125,2
3,100706,University of Alabama in Huntsville,UAH University of Alabama Huntsville,301 Sparkman Dr,Huntsville,AL,35899,1,5,Chuck Karr,...,26620,1,290,1089,Madison County,105,-86.640449,34.724557,91,2
4,100724,Alabama State University,NaN,915 S Jackson Street,Montgomery,AL,36104-0271,1,5,Quinton T. Ross,...,33860,1,388,1101,Montgomery County,102,-86.295677,32.364317,97,1

In [3]:
# Filter for public, 4 year universities only.
public_institution_df = master_df[master_df['SECTOR'] == 1]
public_institution_df.shape

(848, 72)

In [4]:
financial_df = pd.read_csv('../Data/raw_data/2024/unzipped/f2324_f1a.csv', low_memory=False)
financial_df.head()

,UNITID,XF1A01,F1A01,XF1A31,F1A31,XF1A04,F1A04,XF1A05,F1A05,XF1A06,...,XF1N03,F1N03,XF1N04,F1N04,XF1N05,F1N05,XF1N06,F1N06,XF1N07,F1N07
0,100654,R,1.806546e+08,R,2.331945e+08,R,0.000000e+00,R,2.331945e+08,R,...,R,-26221592.0,R,1.157339e+08,R,-4.536222e+07,R,68084358.0,R,2.617002e+08
1,100663,R,2.833082e+09,R,2.285819e+09,R,2.200178e+09,R,4.485996e+09,R,...,R,763456300.0,R,5.909441e+09,R,4.390652e+09,R,13701248.0,R,5.928841e+09
2,100706,R,2.561422e+08,R,2.935960e+08,R,1.943912e+08,R,4.879872e+08,R,...,R,82454317.0,R,5.526640e+08,R,4.151547e+08,R,138687126.0,R,3.122858e+08
3,100724,R,1.527136e+08,R,2.368947e+08,R,7.740740e+05,R,2.376688e+08,R,...,R,21345771.0,R,3.268732e+08,R,0.000000e+00,R,37455000.0,R,1.943673e+08
4,100733,R,9.165526e+06,R,1.651899e+07,R,1.505174e+07,R,3.157073e+07,R,...,R,1514354.0,R,9.830457e+06,R,5.719837e+06,R,0.0,R,1.608599e+08

In [5]:
hr_df = pd.read_csv('../Data/raw_data/2024/unzipped/drvhr2024.csv', low_memory=False)
hr_df.head()

,UNITID,SALTOTL,SALPROF,SALASSC,SALASST,SALINST,SALLECT,SALNRNK,SFTETOTL,SFTEPSTC,...,SFTEBFO,SFTECES,SFTECLAM,SFTEHLTH,SFTEOTHR,SFTESRVC,SFTESALE,SFTEOFAS,SFTENRCM,SFTEPTMM
0,100654,78336.0,106841.0,86486.0,74640.0,54304.0,NaN,67970.0,913.02,318.67,...,25.00,47.67,118.33,3.67,289.68,65.67,0.0,179.67,15.67,28.67
1,100663,113387.0,160333.0,107881.0,88941.0,74679.0,NaN,NaN,10077.32,2917.33,...,1336.67,2094.67,395.00,609.33,1912.33,781.67,0.0,750.33,297.00,83.33
2,100690,55032.0,57436.0,65081.0,50340.0,28188.0,NaN,NaN,58.00,29.00,...,6.00,5.00,0.00,0.00,10.00,0.00,0.0,10.00,0.00,0.00
3,100706,96060.0,139459.0,99067.0,90664.0,74580.0,59101.0,NaN,1529.33,416.33,...,99.33,502.00,108.00,2.67,250.00,106.00,0.0,137.00,7.00,0.00
4,100724,73380.0,89445.0,78941.0,67619.0,51472.0,NaN,39572.0,845.32,261.33,...,44.00,38.33,105.67,7.00,221.33,78.00,8.0,97.00,38.33,0.00

In [6]:
helper_df = public_institution_df.merge(financial_df, how='left', on='UNITID')
join_df = helper_df.merge(hr_df, how='left', on='UNITID')

In [7]:
join_df.head(5)

,UNITID,INSTNM,IALIAS,ADDR,CITY,STABBR,ZIP,FIPS,OBEREG,CHFNM,...,SFTEBFO,SFTECES,SFTECLAM,SFTEHLTH,SFTEOTHR,SFTESRVC,SFTESALE,SFTEOFAS,SFTENRCM,SFTEPTMM
0,100654,Alabama A & M University,AAMU,4900 Meridian Street,Normal,AL,35762,1,5,Dr. Daniel K. Wims,...,25.00,47.67,118.33,3.67,289.68,65.67,0.00,179.67,15.67,28.67
1,100663,University of Alabama at Birmingham,UAB,Administration Bldg Suite 1070,Birmingham,AL,35294-0110,1,5,Ray L. Watts,...,1336.67,2094.67,395.00,609.33,1912.33,781.67,0.00,750.33,297.00,83.33
2,100706,University of Alabama in Huntsville,UAH University of Alabama Huntsville,301 Sparkman Dr,Huntsville,AL,35899,1,5,Chuck Karr,...,99.33,502.00,108.00,2.67,250.00,106.00,0.00,137.00,7.00,0.00
3,100724,Alabama State University,NaN,915 S Jackson Street,Montgomery,AL,36104-0271,1,5,Quinton T. Ross,...,44.00,38.33,105.67,7.00,221.33,78.00,8.00,97.00,38.33,0.00
4,100751,The University of Alabama,NaN,739 University Blvd,Tuscaloosa,AL,35487-0100,1,5,Dr. Stuart R. Bell,...,694.67,506.33,711.00,275.33,1892.66,644.67,29.33,855.33,260.00,103.33

In [8]:
join_df.shape

(848, 385)

# Code below will create missing derived HR dataset for years using EAP files, 2014 - 2024

In [9]:
# 1. The exact 27 columns from your 2022 derived file
derived_2022_columns = [
    'UNITID', 'SALTOTL', 'SALPROF', 'SALASSC', 'SALASST', 'SALINST', 
    'SALLECT', 'SALNRNK', 'SFTETOTL', 'SFTEPSTC', 'SFTEINST', 'SFTERSRC', 
    'SFTEPBSV', 'SFTELCAI', 'SFTELCA', 'SFTEOTIS', 'SFTEMNGM', 'SFTEBFO', 
    'SFTECES', 'SFTECLAM', 'SFTEHLTH', 'SFTEOTHR', 'SFTESRVC', 'SFTESALE', 
    'SFTEOFAS', 'SFTENRCM', 'SFTEPTMM'
]

# 2. Map the EAPCAT numeric codes to the 2022 Column Names
category_mapping = {
    10000: 'SFTETOTL',
    21000: 'SFTEINST',
    22000: 'SFTERSRC',
    23000: 'SFTEPBSV',
    30000: 'SFTEMNGM',
    31000: 'SFTEBFO',
    32000: 'SFTECES',
    33000: 'SFTECLAM',
    34000: 'SFTEHLTH',
    35000: 'SFTESRVC',
    36000: 'SFTESALE',
    37000: 'SFTEOFAS',
    38000: 'SFTENRCM',
    39000: 'SFTEPTMM'
}

# 3. Loop through 2014 to 2020 (range is inclusive of start, exclusive of end)
years = range(2014, 2021)

for year in years:
    input_file = f'../Data/epa14-20/eap{year}_rv.csv'
    output_file = f'../Data/epa14-20/drvhr/drvhr{year}_rv.csv'
    
    # Safely skip years you haven't downloaded yet
    if not os.path.exists(input_file):
        print(f"[-] Missing: {input_file}. Please download it from IPEDS. Skipping...")
        continue
        
    print(f"[+] Processing {input_file}...")
    
    # Load raw data
    eap = pd.read_csv(input_file)
    
    # Filter for only the categories in our mapping dictionary
    target_data = eap[eap['EAPCAT'].isin(category_mapping.keys())].copy()
    
    # Clean the columns to ensure they are numeric
    target_data['EAPFT'] = pd.to_numeric(target_data['EAPFT'], errors='coerce').fillna(0)
    target_data['EAPPT'] = pd.to_numeric(target_data['EAPPT'], errors='coerce').fillna(0)
    
    # Calculate the Federal FTE Formula: Full-Time + (Part-Time / 3)
    target_data['FTE_CALC'] = np.round(target_data['EAPFT'] + (target_data['EAPPT'] / 3))
    
    # Pivot the table to get UNITID on the rows
    hr_simulated = target_data.pivot_table(
        index='UNITID',
        columns='EAPCAT',
        values='FTE_CALC',
        aggfunc='sum'
    ).reset_index()
    
    # Rename the columns using our dictionary
    hr_simulated = hr_simulated.rename(columns=category_mapping)
    
    # --- PAD THE MISSING COLUMNS ---
    # Add any missing columns (like the SALARY columns) and fill them with blanks/NaNs
    for col in derived_2022_columns:
        if col not in hr_simulated.columns:
            hr_simulated[col] = np.nan
            
    # Reorder columns to match the 2022 file exactly
    hr_simulated = hr_simulated[derived_2022_columns]
    
    # Save to CSV
    hr_simulated.to_csv(output_file, index=False)
    print(f"    -> Successfully saved {output_file} with {len(hr_simulated.columns)} columns!\n")
    
print("Data pipeline execution complete for 2014-2020!")

[+] Processing ../Data/epa14-20/eap2014_rv.csv...
    -> Successfully saved ../Data/epa14-20/drvhr/drvhr2014_rv.csv with 27 columns!

[+] Processing ../Data/epa14-20/eap2015_rv.csv...
    -> Successfully saved ../Data/epa14-20/drvhr/drvhr2015_rv.csv with 27 columns!

[+] Processing ../Data/epa14-20/eap2016_rv.csv...
    -> Successfully saved ../Data/epa14-20/drvhr/drvhr2016_rv.csv with 27 columns!

[+] Processing ../Data/epa14-20/eap2017_rv.csv...
    -> Successfully saved ../Data/epa14-20/drvhr/drvhr2017_rv.csv with 27 columns!

[+] Processing ../Data/epa14-20/eap2018_rv.csv...
    -> Successfully saved ../Data/epa14-20/drvhr/drvhr2018_rv.csv with 27 columns!

[+] Processing ../Data/epa14-20/eap2019_rv.csv...
    -> Successfully saved ../Data/epa14-20/drvhr/drvhr2019_rv.csv with 27 columns!

[+] Processing ../Data/epa14-20/eap2020_rv.csv...
    -> Successfully saved ../Data/epa14-20/drvhr/drvhr2020_rv.csv with 27 columns!

Data pipeline execution complete for 2014-2020!

In [10]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path('../Data/raw_data')
YEARS = range(2014, 2025)


def read_ipeds(path):
    """Read an IPEDS csv and normalize headers.

    Encoding varies across years: some files are UTF-8 (a few with a BOM), others are
    Windows-encoded with bytes cp1252 cannot decode. utf-8-sig handles the BOM case and
    latin-1 decodes any byte, so the pair covers every file without failing.
    """
    for encoding in ('utf-8-sig', 'latin-1'):
        try:
            df = pd.read_csv(path, low_memory=False, encoding=encoding)
            break
        except UnicodeDecodeError:
            continue
    df.columns = df.columns.str.strip()
    return df


def pick(folder, *names):
    """First existing file, preferring the _rv (revised) version."""
    for name in names:
        path = folder / name
        if path.exists():
            return path
    return None


for year in YEARS:
    year_dir = BASE_DIR / str(year)
    source_dir = year_dir / 'unzipped' if (year_dir / 'unzipped').exists() else year_dir
    if not source_dir.exists():
        print(f"Skipping {year}: folder not found -> {source_dir}")
        continue

    curr, prev = str(year)[-2:], str(year - 1)[-2:]
    master_file    = pick(source_dir, f'hd{year}.csv')
    financial_file = pick(source_dir, f'f{prev}{curr}_f1a_rv.csv', f'f{prev}{curr}_f1a.csv')
    hr_file        = pick(source_dir, f'drvhr{year}_rv.csv', f'drvhr{year}.csv')

    missing = [n for n, p in [('hd', master_file), ('f1a', financial_file), ('drvhr', hr_file)]
               if p is None]
    if missing:
        print(f"Skipping {year}: missing {missing} in {source_dir}")
        continue

    master_df = read_ipeds(master_file)
    public_institution_df = master_df.loc[master_df['SECTOR'] == 1].copy()

    join_df = (public_institution_df
               .merge(read_ipeds(financial_file), how='left', on='UNITID')
               .merge(read_ipeds(hr_file), how='left', on='UNITID'))

    # Write to the year folder (not the unzipped subfolder).
    output_file = year_dir / f'join_df_{year}.csv'
    join_df.to_csv(output_file, index=False)
    print(f"Saved {output_file}  shape={join_df.shape}")

Saved ..\Data\raw_data\2014\join_df_2014.csv  shape=(725, 416)
Saved ..\Data\raw_data\2015\join_df_2015.csv  shape=(734, 426)
Saved ..\Data\raw_data\2016\join_df_2016.csv  shape=(759, 316)
Saved ..\Data\raw_data\2017\join_df_2017.csv  shape=(775, 316)
Saved ..\Data\raw_data\2018\join_df_2018.csv  shape=(796, 317)
Saved ..\Data\raw_data\2019\join_df_2019.csv  shape=(807, 325)
Saved ..\Data\raw_data\2020\join_df_2020.csv  shape=(806, 386)
Saved ..\Data\raw_data\2021\join_df_2021.csv  shape=(784, 387)
Saved ..\Data\raw_data\2022\join_df_2022.csv  shape=(814, 386)
Saved ..\Data\raw_data\2023\join_df_2023.csv  shape=(822, 386)
Saved ..\Data\raw_data\2024\join_df_2024.csv  shape=(848, 385)

# Add Fall Enrollment (EF) data to the yearly join_df files, 2014-2024

Enrollment is the driver our finance-only panel could not see. Two EF files are merged per year:

- **`ef{year}a`** - fall headcount. This file is **long** (one row per institution x `EFALEVEL`), so it is pivoted to one row per institution before merging.
- **`ef{year}d`** - retention rates and student-to-faculty ratio, already one row per institution.

Files are `_rv` (revised) through 2023 and un-revised for 2024, so the loader prefers `_rv` and falls back to the plain name. The cell is safe to re-run: existing EF columns are dropped before re-merging.

In [11]:
EF_DIR = Path('../Data/ef')
BASE_DIR = Path('../Data/raw_data')
YEARS = range(2014, 2025)

# EF__A is long: one row per UNITID x EFALEVEL. Keep these level codes.
# (Verify the codes against the EF dictionary for your years before relying on them.)
EFALEVEL_MAP = {1: 'EF_TOTAL', 2: 'EF_UNDERGRAD', 12: 'EF_GRADUATE'}

# EF__D is one row per institution; keep these columns if present.
EFD_KEEP = ['RET_PCF', 'RET_PCP', 'STUFACR']


def join_path_for(year):
    """join_df is written to the year folder; also check unzipped/ for files from older runs."""
    for path in (BASE_DIR / str(year) / f'join_df_{year}.csv',
                 BASE_DIR / str(year) / 'unzipped' / f'join_df_{year}.csv'):
        if path.exists():
            return path
    return None


def ef_path(year, letter):
    """EF files are *_rv.csv through 2023 and un-revised for 2024."""
    for name in (f'ef{year}{letter}_rv.csv', f'ef{year}{letter}.csv'):
        path = EF_DIR / name
        if path.exists():
            return path
    return None


def load_ef_a(year):
    """Fall enrollment headcount, pivoted from long to one row per institution."""
    path = ef_path(year, 'a')
    if path is None:
        print(f"    [-] no ef{year}a file found")
        return None
    df = pd.read_csv(path, low_memory=False, encoding='cp1252')
    df.columns = df.columns.str.strip().str.upper()
    if 'EFALEVEL' not in df.columns or 'EFTOTLT' not in df.columns:
        print(f"    [!] {path.name}: EFALEVEL/EFTOTLT missing, skipping")
        return None
    subset = df[df['EFALEVEL'].isin(EFALEVEL_MAP)]
    wide = (subset.pivot_table(index='UNITID', columns='EFALEVEL',
                               values='EFTOTLT', aggfunc='sum')
                  .rename(columns=EFALEVEL_MAP)
                  .reset_index())
    wide.columns.name = None
    return wide


def load_ef_d(year):
    """Retention rates and student-to-faculty ratio (already one row per institution)."""
    path = ef_path(year, 'd')
    if path is None:
        print(f"    [-] no ef{year}d file found")
        return None
    df = pd.read_csv(path, low_memory=False, encoding='cp1252')
    df.columns = df.columns.str.strip().str.upper()
    missing = [c for c in EFD_KEEP if c not in df.columns]
    if missing:
        print(f"    [!] {path.name}: columns not found -> {missing}")
    keep = ['UNITID'] + [c for c in EFD_KEEP if c in df.columns]
    return df[keep].drop_duplicates('UNITID')


EF_COLS = list(EFALEVEL_MAP.values()) + EFD_KEEP

for year in YEARS:
    join_path = join_path_for(year)
    if join_path is None:
        print(f"Skipping {year}: no join_df_{year}.csv found in "
              f"{BASE_DIR / str(year)} or its unzipped/ subfolder")
        continue

    join_df = pd.read_csv(join_path, low_memory=False)
    # Drop any EF columns from a previous run so this cell is safe to re-execute.
    join_df = join_df.drop(columns=[c for c in EF_COLS if c in join_df.columns])
    start_cols, start_rows = join_df.shape[1], join_df.shape[0]

    for loader in (load_ef_a, load_ef_d):
        block = loader(year)
        if block is not None:
            join_df = join_df.merge(block, how='left', on='UNITID')

    # A merge that changes the row count means duplicate UNITIDs slipped through.
    assert join_df.shape[0] == start_rows, f"{year}: row count changed on EF merge"

    join_df.to_csv(join_path, index=False)
    coverage = {c: int(join_df[c].notna().sum()) for c in EF_COLS if c in join_df.columns}
    print(f"{year}: {start_cols} -> {join_df.shape[1]} cols | rows {join_df.shape[0]} | "
          f"non-null {coverage} | {join_path.parent}")

print("\nEF merge complete.")

2014: 416 -> 422 cols | rows 725 | non-null {'EF_TOTAL': 723, 'EF_UNDERGRAD': 705, 'EF_GRADUATE': 570, 'RET_PCF': 628, 'RET_PCP': 580, 'STUFACR': 705} | ..\Data\raw_data\2014
2015: 426 -> 432 cols | rows 734 | non-null {'EF_TOTAL': 732, 'EF_UNDERGRAD': 711, 'EF_GRADUATE': 573, 'RET_PCF': 626, 'RET_PCP': 585, 'STUFACR': 711} | ..\Data\raw_data\2015
2016: 316 -> 322 cols | rows 759 | non-null {'EF_TOTAL': 758, 'EF_UNDERGRAD': 737, 'EF_GRADUATE': 579, 'RET_PCF': 627, 'RET_PCP': 574, 'STUFACR': 737} | ..\Data\raw_data\2016
2017: 316 -> 322 cols | rows 775 | non-null {'EF_TOTAL': 772, 'EF_UNDERGRAD': 751, 'EF_GRADUATE': 578, 'RET_PCF': 631, 'RET_PCP': 586, 'STUFACR': 751} | ..\Data\raw_data\2017
2018: 317 -> 323 cols | rows 796 | non-null {'EF_TOTAL': 790, 'EF_UNDERGRAD': 769, 'EF_GRADUATE': 584, 'RET_PCF': 629, 'RET_PCP': 590, 'STUFACR': 769} | ..\Data\raw_data\2018
2019: 325 -> 331 cols | rows 807 | non-null {'EF_TOTAL': 770, 'EF_UNDERGRAD': 753, 'EF_GRADUATE': 567, 'RET_PCF': 616, 'RET_PCP': 567, 'STUFACR': 753} | ..\Data\raw_data\2019
2020: 386 -> 392 cols | rows 806 | non-null {'EF_TOTAL': 776, 'EF_UNDERGRAD': 759, 'EF_GRADUATE': 563, 'RET_PCF': 619, 'RET_PCP': 573, 'STUFACR': 759} | ..\Data\raw_data\2020
2021: 387 -> 393 cols | rows 784 | non-null {'EF_TOTAL': 779, 'EF_UNDERGRAD': 765, 'EF_GRADUATE': 561, 'RET_PCF': 620, 'RET_PCP': 591, 'STUFACR': 765} | ..\Data\raw_data\2021
2022: 386 -> 392 cols | rows 814 | non-null {'EF_TOTAL': 805, 'EF_UNDERGRAD': 791, 'EF_GRADUATE': 570, 'RET_PCF': 645, 'RET_PCP': 597, 'STUFACR': 791} | ..\Data\raw_data\2022
2023: 386 -> 392 cols | rows 822 | non-null {'EF_TOTAL': 819, 'EF_UNDERGRAD': 805, 'EF_GRADUATE': 576, 'RET_PCF': 647, 'RET_PCP': 606, 'STUFACR': 805} | ..\Data\raw_data\2023
2024: 385 -> 391 cols | rows 848 | non-null {'EF_TOTAL': 847, 'EF_UNDERGRAD': 833, 'EF_GRADUATE': 578, 'RET_PCF': 650, 'RET_PCP': 606, 'STUFACR': 833} | ..\Data\raw_data\2024

EF merge complete.

# Add EAP faculty-tenure detail to the yearly join_df files

IPEDS EAP (Employees by Assigned Position) gives instructional headcount by tenure status, which lets us measure **adjunctification** - the shift toward contingent faculty that the Introduction names as a harm (Ehrenberg & Zhang 2005; Bettinger & Long 2010; AAUP 2025). Instructional staff are `OCCUPCAT == 210`; tenure status is `FACSTAT` (20 tenured, 30 tenure-track, 40 not-on-track).

**Coverage caveat:** the available files span **2014-2020 only**. Rows for 2021-2024 will have blank tenure columns, which matters because the rolling-origin test years (2021, 2022) fall in that gap - so these features cannot influence the held-out evaluation until the 2021-2024 EAP files are added.

In [12]:
EAP_DIR = Path('../Data/epa14-20')

# Instructional staff (OCCUPCAT 210) by tenure status (FACSTAT):
#   0 = total, 20 = tenured, 30 = on tenure track, 40 = not on track.
FACSTAT_MAP = {20: 'EAP_INST_TENURED', 30: 'EAP_INST_TENURETRACK', 40: 'EAP_INST_NOTRACK'}
EAP_COLS = ['EAP_INST_TOTAL', 'EAP_INST_PT'] + list(FACSTAT_MAP.values())


def eap_path(year):
    for name in (f'eap{year}_rv.csv', f'eap{year}.csv'):
        path = EAP_DIR / name
        if path.exists():
            return path
    return None


def load_eap(year):
    path = eap_path(year)
    if path is None:
        print(f"    [-] no EAP file for {year}")
        return None
    df = read_ipeds(path)
    df.columns = df.columns.str.upper()
    inst = df[df['OCCUPCAT'] == 210]
    if inst.empty:
        print(f"    [!] {path.name}: no OCCUPCAT==210 rows")
        return None
    total = (inst[inst['FACSTAT'] == 0]
             .groupby('UNITID')
             .agg(EAP_INST_TOTAL=('EAPTOT', 'sum'), EAP_INST_PT=('EAPPT', 'sum'))
             .reset_index())
    status = (inst[inst['FACSTAT'].isin(FACSTAT_MAP)]
              .pivot_table(index='UNITID', columns='FACSTAT', values='EAPTOT', aggfunc='sum')
              .rename(columns=FACSTAT_MAP).reset_index())
    status.columns.name = None
    return total.merge(status, how='outer', on='UNITID')


for year in YEARS:
    join_path = join_path_for(year)
    if join_path is None:
        print(f"Skipping {year}: no join_df file found")
        continue

    join_df = pd.read_csv(join_path, low_memory=False)
    join_df = join_df.drop(columns=[c for c in EAP_COLS if c in join_df.columns])
    start_cols, start_rows = join_df.shape[1], join_df.shape[0]

    block = load_eap(year)
    if block is not None:
        join_df = join_df.merge(block, how='left', on='UNITID')

    assert join_df.shape[0] == start_rows, f"{year}: row count changed on EAP merge"
    join_df.to_csv(join_path, index=False)
    coverage = {c: int(join_df[c].notna().sum()) for c in EAP_COLS if c in join_df.columns}
    print(f"{year}: {start_cols} -> {join_df.shape[1]} cols | non-null {coverage or 'EAP absent'}")

print("\nEAP merge complete.")

2014: 422 -> 427 cols | non-null {'EAP_INST_TOTAL': 716, 'EAP_INST_PT': 716, 'EAP_INST_TENURED': 686, 'EAP_INST_TENURETRACK': 680, 'EAP_INST_NOTRACK': 710}
2015: 432 -> 437 cols | non-null {'EAP_INST_TOTAL': 725, 'EAP_INST_PT': 725, 'EAP_INST_TENURED': 693, 'EAP_INST_TENURETRACK': 685, 'EAP_INST_NOTRACK': 721}
2016: 322 -> 327 cols | non-null {'EAP_INST_TOTAL': 750, 'EAP_INST_PT': 750, 'EAP_INST_TENURED': 712, 'EAP_INST_TENURETRACK': 705, 'EAP_INST_NOTRACK': 744}
2017: 322 -> 327 cols | non-null {'EAP_INST_TOTAL': 760, 'EAP_INST_PT': 760, 'EAP_INST_TENURED': 722, 'EAP_INST_TENURETRACK': 711, 'EAP_INST_NOTRACK': 753}
2018: 323 -> 328 cols | non-null {'EAP_INST_TOTAL': 777, 'EAP_INST_PT': 777, 'EAP_INST_TENURED': 720, 'EAP_INST_TENURETRACK': 709, 'EAP_INST_NOTRACK': 764}
2019: 331 -> 336 cols | non-null {'EAP_INST_TOTAL': 759, 'EAP_INST_PT': 759, 'EAP_INST_TENURED': 706, 'EAP_INST_TENURETRACK': 695, 'EAP_INST_NOTRACK': 754}
2020: 392 -> 397 cols | non-null {'EAP_INST_TOTAL': 766, 'EAP_INST_PT': 766, 'EAP_INST_TENURED': 703, 'EAP_INST_TENURETRACK': 686, 'EAP_INST_NOTRACK': 759}
    [-] no EAP file for 2021
2021: 393 -> 393 cols | non-null EAP absent
    [-] no EAP file for 2022
2022: 392 -> 392 cols | non-null EAP absent
    [-] no EAP file for 2023
2023: 392 -> 392 cols | non-null EAP absent
    [-] no EAP file for 2024
2024: 391 -> 391 cols | non-null EAP absent

EAP merge complete.

# Combine the yearly files into one master panel, 2014-2024

Stacks every `join_df_{year}.csv` into a single institution-by-year panel tagged with `YEAR`. Run this after any new data source is merged above, so the master panel always reflects the latest additions.

Two things the naive `pd.concat` misses, handled here:
- **Header drift** - a few yearly files carry trailing spaces in column names (e.g. `SFTEPTMM   `), which would otherwise become separate columns. Names are stripped and duplicates collapsed.
- **Schema drift** - the yearly files do not share an identical column set, so `concat` takes the union and fills `NaN` where a year lacked a column. The cell reports how many columns are affected so this is visible rather than silent.

In [13]:
frames = []
for year in YEARS:
    path = join_path_for(year)
    if path is None:
        print(f"[-] {year}: no join_df file found, skipping")
        continue

    df = pd.read_csv(path, low_memory=False)
    # Normalize headers so trailing-space variants collapse into one column.
    df.columns = df.columns.str.strip()
    df = df.loc[:, ~df.columns.duplicated()]
    frames.append(df.assign(YEAR=year))
    print(f"[+] {year}: {len(df)} rows, {df.shape[1]} cols")

assert frames, "No yearly files loaded -- check BASE_DIR."
master_panel_df = pd.concat(frames, ignore_index=True)

# One row per institution-year.
before = len(master_panel_df)
master_panel_df = (master_panel_df
                   .drop_duplicates(['UNITID', 'YEAR'])
                   .sort_values(['UNITID', 'YEAR'])
                   .reset_index(drop=True))
if len(master_panel_df) < before:
    print(f"\ndropped {before - len(master_panel_df)} duplicate (UNITID, YEAR) rows")

# How much of the width is an artifact of schema drift across years?
column_sets = [set(f.columns) for f in frames]
in_all_years = set.intersection(*column_sets)
print(f"\nMaster panel: {master_panel_df.shape[0]} institution-years x {master_panel_df.shape[1]} cols")
print(f"  years        : {master_panel_df['YEAR'].min()}-{master_panel_df['YEAR'].max()} "
      f"({master_panel_df['YEAR'].nunique()} loaded)")
print(f"  institutions : {master_panel_df['UNITID'].nunique()}")
print(f"  columns present in every year: {len(in_all_years)} "
      f"({master_panel_df.shape[1] - len(in_all_years)} appear in only some years)")

[+] 2014: 725 rows, 427 cols
[+] 2015: 734 rows, 437 cols
[+] 2016: 759 rows, 327 cols
[+] 2017: 775 rows, 327 cols
[+] 2018: 796 rows, 328 cols
[+] 2019: 807 rows, 336 cols

C:\Users\jimmy\AppData\Local\Temp\ipykernel_36968\3107774272.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  frames.append(df.assign(YEAR=year))
C:\Users\jimmy\AppData\Local\Temp\ipykernel_36968\3107774272.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  frames.append(df.assign(YEAR=year))
C:\Users\jimmy\AppData\Local\Temp\ipykernel_36968\3107774272.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  frames.append(df.assign(YEAR=year))
C:\Users\jimmy\AppData\Local\Temp\ipykernel_36968\3107774272.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  frames.append(df.assign(YEAR=year))
C:\Users\jimmy\AppData\Local\Temp\ipykernel_36968\3107774272.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  frames.append(df.assign(YEAR=year))
C:\Users\jimmy\AppData\Local\Temp\ipykernel_36968\3107774272.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  frames.append(df.assign(YEAR=year))
C:\Users\jimmy\AppData\Local\Temp\ipykernel_36968\3107774272.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  frames.append(df.assign(YEAR=year))

[+] 2020: 806 rows, 397 cols
[+] 2021: 784 rows, 393 cols
[+] 2022: 814 rows, 392 cols
[+] 2023: 822 rows, 392 cols
[+] 2024: 848 rows, 391 cols

C:\Users\jimmy\AppData\Local\Temp\ipykernel_36968\3107774272.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  frames.append(df.assign(YEAR=year))
C:\Users\jimmy\AppData\Local\Temp\ipykernel_36968\3107774272.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  frames.append(df.assign(YEAR=year))
C:\Users\jimmy\AppData\Local\Temp\ipykernel_36968\3107774272.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  frames.append(df.assign(YEAR=year))
C:\Users\jimmy\AppData\Local\Temp\ipykernel_36968\3107774272.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  frames.append(df.assign(YEAR=year))

Master panel: 8670 institution-years x 547 cols
  years        : 2014-2024 (11 loaded)
  institutions : 899
  columns present in every year: 291 (256 appear in only some years)

## Build the prediction target

`TARGET_STAFF_CUT` = a decline of 5% or more in instructional FTE staff over a **two-year** horizon (`t -> t+2`), which matches the 18-24 month lead time the project promises. The label is forward-looking, computed per institution across a gap-free window, and left as `<NA>` where no year `t+2` exists - those rows are unlabeled, not negative.

`TARGET_VULNERABLE_TOTAL` (any decline in total staff) is kept as a secondary label for comparison.

In [14]:
STAFF_COL = 'SFTEINST'      # instructional FTE staff
MIN_BASE  = 1.0             # floor on the base year so tiny denominators don't distort the ratio
HORIZON   = 2               # years ahead: 2 = a cut over t -> t+2

group = master_panel_df.groupby('UNITID')


def forward_pct(col, horizon=HORIZON):
    """Forward % change (t -> t+horizon), valid only across a gap-free window with a usable base."""
    current = master_panel_df[col]
    future = group[col].shift(-horizon)
    future_year = group['YEAR'].shift(-horizon)
    valid = ((future_year - master_panel_df['YEAR']).eq(horizon)
             & current.notna() & future.notna() & current.ge(MIN_BASE))
    return ((future - current) / current * 100).where(valid), valid


pct_inst, valid_inst = forward_pct(STAFF_COL)
pct_totl, valid_totl = forward_pct('SFTETOTL')

master_panel_df = master_panel_df.assign(
    FTE_INST_PCT_CHANGE_2Y  = pct_inst,
    FTE_TOTL_PCT_CHANGE_2Y  = pct_totl,
    TARGET_STAFF_CUT        = (pct_inst <= -5).where(valid_inst).astype('Int64'),
    TARGET_VULNERABLE_TOTAL = (pct_totl < 0).where(valid_totl).astype('Int64'),
)

for target in ['TARGET_STAFF_CUT', 'TARGET_VULNERABLE_TOTAL']:
    labeled = master_panel_df[target].notna()
    print(f"{target}: labeled={int(labeled.sum())} of {len(master_panel_df)}, "
          f"positives={int(master_panel_df[target].sum())}, "
          f"rate={master_panel_df.loc[labeled, target].mean() * 100:.1f}%")

labeled_years = master_panel_df.loc[master_panel_df['TARGET_STAFF_CUT'].notna(), 'YEAR']
print(f"\nlabeled predictor years: {labeled_years.min()}-{labeled_years.max()} "
      f"(the last {HORIZON} years cannot be labeled yet)")

master_panel_df[['UNITID', 'YEAR', STAFF_COL, 'FTE_INST_PCT_CHANGE_2Y', 'TARGET_STAFF_CUT']].head(10)

TARGET_STAFF_CUT: labeled=6711 of 8670, positives=1646, rate=24.5%
TARGET_VULNERABLE_TOTAL: labeled=6725 of 8670, positives=3092, rate=46.0%

labeled predictor years: 2014-2022 (the last 2 years cannot be labeled yet)

C:\Users\jimmy\AppData\Local\Temp\ipykernel_36968\3013984792.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  master_panel_df = master_panel_df.assign(
C:\Users\jimmy\AppData\Local\Temp\ipykernel_36968\3013984792.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  master_panel_df = master_panel_df.assign(
C:\Users\jimmy\AppData\Local\Temp\ipykernel_36968\3013984792.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  master_panel_df = master_panel_df.assign(
C:\Users\jimmy\AppData\Local\Temp\ipykernel_36968\3013984792.py:21: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  master_panel_df = master_panel_df.assign(

   UNITID  YEAR  SFTEINST  FTE_INST_PCT_CHANGE_2Y  TARGET_STAFF_CUT
0  100654  2014     247.0               16.599190                 0
1  100654  2015     279.0                4.659498                 0
2  100654  2016     288.0                1.041667                 0
3  100654  2017     292.0               -4.452055                 0
4  100654  2018     291.0               -0.343643                 0
5  100654  2019     279.0              -13.978495                 1
6  100654  2020     290.0                1.724138                 0
7  100654  2021     240.0               26.666667                 0
8  100654  2022     295.0                8.023729                 0
9  100654  2023     304.0                     NaN              <NA>

## Save the master panel

This file is the single input to the modeling notebook. Re-run the cells above whenever a new IPEDS component is added, and this file will pick it up.

In [15]:
output_path = Path('../Data/master_panel_df.csv')
master_panel_df.to_csv(output_path, index=False)
print(f"saved {output_path}  shape={master_panel_df.shape}")

saved ..\Data\master_panel_df.csv  shape=(8670, 551)